//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.Configuration;
using System.Diagnostics;
using System.Drawing;
using System.Runtime.CompilerServices;
using System.Windows.Forms;

namespace RobX.Controller.Properties {
    
    
    [CompilerGenerated()]
    [GeneratedCode("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("127.0.0.1")]
        public string SimulatorIP {
            get {
                return ((string)(this["SimulatorIP"]));
            }
            set {
                this["SimulatorIP"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("127.0.0.1")]
        public string RealIP {
            get {
                return ((string)(this["RealIP"]));
            }
            set {
                this["RealIP"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("1371")]
        public string SimulatorPort {
            get {
                return ((string)(this["SimulatorPort"]));
            }
            set {
                this["SimulatorPort"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("1370")]
        public string RealPort {
            get {
                return ((string)(this["RealPort"]));
            }
            set {
                this["RealPort"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("0")]
        public int RobotType {
            get {
                return ((int)(this["RobotType"]));
            }
            set {
                this["RobotType"] = value;
            }
        }
        
        [ApplicationScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("Up")]
        public Keys ForwardKey {
            get {
                return ((Keys)(this["ForwardKey"]));
            }
        }
        
        [ApplicationScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("Down")]
        public Keys BackwardKey {
            get {
                return ((Keys)(this["BackwardKey"]));
            }
        }
        
        [ApplicationScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("Right")]
        public Keys RotateClockwiseKey {
            get {
                return ((Keys)(this["RotateClockwiseKey"]));
            }
        }
        
        [ApplicationScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("Left")]
        public Keys RotateCounterClockwiseKey {
            get {
                return ((Keys)(this["RotateCounterClockwiseKey"]));
            }
        }
        
        [ApplicationScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("ShiftKey")]
        public Keys StopKey {
            get {
                return ((Keys)(this["StopKey"]));
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("480, 561")]
        public Size FormSize {
            get {
                return ((Size)(this["FormSize"]));
            }
            set {
                this["FormSize"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("0, 0")]
        public Point FormPosition {
            get {
                return ((Point)(this["FormPosition"]));
            }
            set {
                this["FormPosition"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("1")]
        public double SimulationSpeed {
            get {
                return ((double)(this["SimulationSpeed"]));
            }
            set {
                this["SimulationSpeed"] = value;
            }
        }
        
        [ApplicationScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("F10")]
        public Keys GlobalStopKey {
            get {
                return ((Keys)(this["GlobalStopKey"]));
            }
        }
        
        [ApplicationScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("F5")]
        public Keys StartKey {
            get {
                return ((Keys)(this["StartKey"]));
            }
        }
        
        [ApplicationScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("F12")]
        public Keys ToggleKeyboardControl {
            get {
                return ((Keys)(this["ToggleKeyboardControl"]));
            }
        }
    }
}
